ype_parameters_2302": "I membri statici non possono fare riferimento a parametri di tipo classe.",
  "Static_property_0_conflicts_with_built_in_property_Function_0_of_constructor_function_1_2699": "La proprietà statica '{0}' è in conflitto con la proprietà predefinita 'Function.{0}' della funzione del costruttore '{1}'.",
  "String_literal_expected_1141": "È previsto un valore letterale stringa.",
  "String_literal_import_and_export_names_are_not_supported_when_the_module_flag_is_set_to_es2015_or_es_18057": "I nomi di importazione ed esportazione di valori letterali stringa non sono supportati quando il flag '--module' è impostato su 'es2015' o 'es2020'.",
  "String_literal_with_double_quotes_expected_1327": "È previsto un valore letterale stringa con virgolette doppie.",
  "Stylize_errors_and_messages_using_color_and_context_experimental_6073": "Applica stili a errori e messaggi usando colore e contesto (sperimentale).",
  "Subpattern_flags_must_be_present_when_there_is_a_minus_sign_1504": "Quando è presente un segno meno, devono essere presenti flag di criteri secondari.",
  "Subsequent_property_declarations_must_have_the_same_type_Property_0_must_be_of_type_1_but_here_has_t_2717": "Le dichiarazioni di proprietà successive devono essere dello stesso tipo. La proprietà '{0}' deve essere di tipo '{1}', ma qui è di tipo '{2}'.",
  "Subsequent_variable_declarations_must_have_the_same_type_Variable_0_must_be_of_type_1_but_here_has_t_2403": "Le dichiarazioni di variabili successive devono essere dello stesso tipo. La variabile '{0}' deve essere di tipo '{1}', mentre è di tipo '{2}'.",
  "Substitution_0_for_pattern_1_has_incorrect_type_expected_string_got_2_5064": "Il tipo della sostituzione '{0}' per il criterio '{1}' non è corretto. È previsto 'string', ma è stato ottenuto '{2}'.",
  "Substitution_0_in_pattern_1_can_have_at_most_one_Asterisk_character_5062": "La sostituzione '{0}' nel criterio '{1}' può contenere al massimo un carattere '*'.",
  "Substitutions_for_pattern_0_should_be_an_array_5063": "Le sostituzioni per il criterio '{0}' devono essere una matrice.",
  "Substitutions_for_pattern_0_shouldn_t_be_an_empty_array_5066": "Le sostituzioni per il criterio '{0}' non devono essere una matrice vuota.",
  "Successfully_created_a_tsconfig_json_file_6071": "La creazione di un file tsconfig.json è riuscita.",
  "Super_calls_are_not_permitted_outside_constructors_or_in_nested_functions_inside_constructors_2337": "Le chiamate super non sono consentite all'esterno di costruttori o nelle funzioni annidate all'interno di costruttori.",
  "Suppress_excess_property_checks_for_object_literals_6072": "Elimina i controlli delle proprietà in eccesso per i valori letterali di oggetto.",
  "Suppress_noImplicitAny_errors_for_indexing_objects_lacking_index_signatures_6055": "Non visualizza gli errori noImplicitAny per gli oggetti di indicizzazione in cui mancano le firme dell'indice.",
  "Suppress_noImplicitAny_errors_when_indexing_objects_that_lack_index_signatures_6703": "Disabilita gli errori 'noImplicitAny' durante l'indicizzazione di oggetti in cui mancano le firme dell'indice.",
  "Switch_each_misused_0_to_1_95138": "Cambiare ogni '{0}' non usato correttamente in '{1}'",
  "Synchronously_call_callbacks_and_update_the_state_of_directory_watchers_on_platforms_that_don_t_supp_6704": "Chiama in modo sincrono i callback e aggiorna lo stato dei watcher di directory in piattaforme che non supportano il controllo ricorsivo in modo nativo.",
  "Syntax_Colon_0_6023": "Sintassi: {0}",
  "Tag_0_expects_at_least_1_arguments_but_the_JSX_factory_2_provides_at_most_3_6229": "Con il tag '{0}' sono previsti almeno '{1}' argomenti, ma la factory JSX '{2}' ne fornisce al massimo '{3}'.",
  "Tagged_template_expressions_are_not_permitted_in_an_optional_chain_1358": "Le espressioni di modello con tag non sono consentite in una catena facoltativa.",
  "Target_allows_only_0_element_s_but_source_may_have_more_2621": "La destinazione consente solo {0} elemento/i ma l'origine potrebbe contenerne di più.",
  "Target_requires_0_element_s_but_source_may_have_fewer_2620": "La destinazione richiede {0} elemento/i ma l'origine potrebbe contenerne di meno.",
  "Target_signature_provides_too_few_arguments_Expected_0_or_more_but_got_1_2849": "La firma di destinazione fornisce un numero insufficiente di argomenti. {0} o più elementi previsti, ma {1} effettivi.",
  "The_0_modifier_can_only_be_used_in_TypeScript_files_8009": "Il modificatore '{0}' può essere usato solo in file TypeScript.",
  "The_0_operator_cannot_be_applied_to_type_symbol_2469": "Non è possibile applicare l'operatore '{0}' al tipo 'symbol'.",
  "The_0_operator_is_not_allowed_for_boolean_types_Consider_using_1_instead_2447": "L'operatore '{0}' non è consentito per i tipi booleani. Provare a usare '{1}'.",
  "The_0_property_of_an_async_iterator_must_be_a_method_2768": "La proprietà '{0}' di un iteratore asincrono deve essere un metodo.",
  "The_0_property_of_an_iterator_must_be_a_method_2767": "La proprietà '{0}' di un iteratore deve essere un metodo.",
  "The_Object_type_is_assignable_to_very_few_other_types_Did_you_mean_to_use_the_any_type_instead_2696": "Il tipo 'Object' può essere assegnato a un numero molto limitato di altri tipi. Si intendeva usare il tipo 'any'?",
  "The_Unicode_u_flag_and_the_Unicode_Sets_v_flag_cannot_be_set_simultaneously_1502": "Non è possibile impostare contemporaneamente i flag Unicode (u) e Unicode Sets (v).",
  "The_arguments_object_cannot_be_referenced_in_an_arrow_function_in_ES5_Consider_using_a_standard_func_2496": "Non è possibile fare riferimento all'oggetto 'arguments' in una funzione arrow in ES5. Provare a usare un'espressione di funzione standard.",
  "The_arguments_object_cannot_be_referenced_in_an_async_function_or_method_in_ES5_Consider_using_a_sta_2522": "Non è possibile fare riferimento all'oggetto 'arguments' in un metodo o una funzione asincrona in ES5. Provare a usare un metodo o una funzione standard.",
  "The_body_of_an_if_statement_cannot_be_the_empty_statement_1313": "Il corpo di un'istruzione 'if' non può essere l'istruzione vuota.",
  "The_call_would_have_succeeded_against_this_implementation_but_implementation_signatures_of_overloads_2793": "La chiamata sarebbe riuscita 